# Generated by Django 5.0.4 on 2024-05-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('datetime', 'currency_code')},
        ),
    ]
